CREATE TABLE "GCG_6398_FLX_QTY" (
 "FLEX_SCHD" CHAR(6),
 "JOB_SUFF" CHAR(10),
 "SEQ" CHAR(6),
 "QTY_GOOD" SMALLINT,
 "QTY_SCRAP" SMALLINT,
 "FLAG_LEAVE" CHAR(1) DEFAULT 'N',
 "FLAG_CLOSE" CHAR(1) DEFAULT 'N' );